version: "3.8"

services:

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes: 
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks:
      - test_network

  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./docker/app/php.dockerfile
    container_name: ${APP_NAME}_php
    volumes: 
      - .:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - test_network 

  #Composer Service
  composer:
    image: composer:latest
    container_name: ${APP_NAME}_composer
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php
    networks:
      - test_network    

  #NPM Service
  npm:
    image: node:14.16.1
    container_name: ${APP_NAME}_npm
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  #Artisan Service
  artisan:
    build: 
      context: .
      dockerfile: ./docker/app/php.dockerfile
    container_name: ${APP_NAME}_artisan
    volumes: 
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - test_network

#Docker Networks
networks:
  test_network: